from courses_platform.service.course.courses_api import CoursesApi
from courses_platform.service.course.courses_detail_api import CoursesDetailApi
from courses_platform.service.course.enrollments_api import EnrollmentsApi
